/**
 * Copyright (c) 2019, kagal "keinepartei" (https://github.com/keinepartei).
 * 
 * Bündnis90/Die Grünen Content Blocker Browser Plug-In
 * (https://github.com/keinepartei/gruenen-blocker-plugin) is licensed under the
 * GNU LGPL3.0 from 29 June 2007
 * (https://www.gnu.org/licenses/lgpl-3.0.en.html).
 * 
 * Content blocker template for instagram.com.
 * 
 * Original source code is from "l2ig" (https://github.com/l2ig) licensed under
 * the ISC License by the Internet Systems Consortium (www.isc.org)
 * https://github.com/dieparteidiepartei/afd-blocker-plugin/app/scripts/blocker_instagram.js
 * commit ef1ab45c00aec9e241f0d38c7621d7f97fa3ebb8.
 */
console.log("Call content blocker.");

import { Blocker } from "./blocker";

const blocker = new Blocker([
    {
        selector: 'article',
        type: 'big'
    },
    {
        selector: `li[style="opacity: 1; width: 200px;"]`,
    }
]);

require("./run_blocker").run(blocker);

/**
 * Instagram.com uses teaser images with often only a alt tag generated by
 * Instagram itself.
 */
console.log("Call content blocker for URL parts.");

function blockPostsOnAfDPage() {
    const posts = [];
    for (let i = 0; i < document.querySelector("article").querySelector(`[style*="flex-direction: column;"]`).children.length; i++) {
        for (let j = 0; j < document.querySelector("article").querySelector(`[style*="flex-direction: column;"]`).children[i].children.length; j++) {
            posts.push({
                element: document.querySelector("article").querySelector(`[style*="flex-direction: column;"]`).children[i].children[j],
                type: "small"
            })
        }
    }
    addBlocker(posts);
}

let mutationObserver = new MutationObserver(mutations => {
    if (document.location.href.match(/(gruene)/i))
        blockPostsOnAfDPage();
});
mutationObserver.observe(document.documentElement, {
    childList: true,
    subtree: true,
});